### ISSUE TITLE
Hi I have something to say

### ISSUE THREAD

**Issue by CoolCodingTeen231** [iiPythonx/xpp#5]
in your git repository called RoBot, it doesnt even work lol. I tried to make it work but it didnt. I recommend you will update it so it will work also I recommend you use this packages:
pygetwindow
pyautogui
pydirectinput
They are tools that can really help you cause your code could be outdated, Thank you for reading and bye

**Comment by iiPythonx** [comment]
RoBot was an experiment back when I hardly knew what I was doing. I had no plans on maintaining it past that, hence why I archived it in 2021. Last time I checked (mid-2022) it worked just fine, but if you can provide some error details I could help you with troubleshooting it.  

Regardless, I have no plans on updating it. You would honestly be better off using something like Synapse X and writing your own movement code in Lua. That would give you way more options then RoBot ever could.

**Comment by CoolCodingTeen231** [comment]
It can't even find Roblox instance even if I kept the window open

**Comment by CoolCodingTeen231** [comment]
Like it should work

**Comment by CoolCodingTeen231** [comment]
@iiPythonx and you probably want me banned from Roblox obviously

**Comment by iiPythonx** [comment]
I never said I wanted you banned from Roblox?

**Comment by CoolCodingTeen231** [comment]
@iiPythonx synapse x will get me banned bruh

**Comment by CoolCodingTeen231** [comment]
And a Roblox developer is 3x Better than me

**Comment by iiPythonx** [comment]
Synapse was a suggestion, and it would obviously require the use of an alt or some other bypass mechanism.  
If you want to stick with RoBot, then can you could post the output of:
```py
import pygetwindow
print(pygetwindow.getWindowsWithTitle("Roblox"))
```
That would be very helpful as I have no clue if pygetwindow still works 3+ years later.

**Comment by iiPythonx** [comment]
Since you magically stopped responding, I'm going to delete this issue since it's in a completely unrelated repo.  
If you seriously still have issues then just send me an email at [ben@iipython.dev](mailto:ben@iipython.dev).
