### ISSUE TITLE
X++ Name

### ISSUE THREAD

**Issue by ianjensenisme** [iiPythonx/xpp#6]
Hi, I think you may eventually run into issues if you stick with the name 'X++', as a language by that name is already owned by Microsoft: https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/xpp-language-reference .

I was searching for something pertaining to the Microsoft language and stumbled upon this repo, which makes me think that other X++ devs might wander in here as well.

**Comment by iiPythonx** [comment]
Thanks for the notice, I was aware that x++ was already a thing although I never really thought anybody would end up here while looking for the much more well-known and popular Microsoft variant.

I'll definitely look into doing something about the name, as I was planning a rebrand at some point anyways.

**Comment by peakizt** [comment]
rename it peak cuz am peak
